// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIqckUW9y9edDlaFkDm8jShRHuwzrunpk',
    appId: '1:693990598755:web:8984b4f88aed6117443056',
    messagingSenderId: '693990598755',
    projectId: 'flutter-proje-393e1',
    authDomain: 'flutter-proje-393e1.firebaseapp.com',
    storageBucket: 'flutter-proje-393e1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb3Iy9sM_4KlorTFSkEJ0kdGCmevVXzuI',
    appId: '1:693990598755:android:0b05e715dad8af89443056',
    messagingSenderId: '693990598755',
    projectId: 'flutter-proje-393e1',
    storageBucket: 'flutter-proje-393e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD020rmR8XfOyAjrnd6R4bhnnrM8TUdScc',
    appId: '1:693990598755:ios:998a33da2571e991443056',
    messagingSenderId: '693990598755',
    projectId: 'flutter-proje-393e1',
    storageBucket: 'flutter-proje-393e1.appspot.com',
    iosClientId: '693990598755-64obd57begnif44jeissbnunhqa0rtqr.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobilprogramlamaodev',
  );
}
